### ISSUE TITLE
Package.json requires a run/start script

### ISSUE THREAD

**Issue by cduarte3** [Add00/DocBot#2]
### In the package.json file, a run/start script is required in order to avoid calling the filename every time in the command. This will allow for better interaction with the CLI tool.

<br>

![image](https://github.com/user-attachments/assets/87f9ef56-8170-40ef-b24f-20a8dce5735a)

**Comment by Add00** [comment]
added `docbot` command to resolve this can be used as follows: `npm run docbot -- myFile.js`
