### ISSUE TITLE
Format code / remove old comments

### ISSUE THREAD

**Issue by cduarte3** [Add00/DocBot#6]
Use a formatter such as prettier, and remove any old comments / comment blocks that were left in the source code.

Code looked fine to me, but for extra touch ups, would advise using a formatter. Doing so helps the code stay more compact in certain functions and overall structure, and helps with overall readability.

**Comment by Add00** [comment]
Makes sense, depreciated code has been removed,and remaining code formatted in [Bug fixes](https://github.com/Add00/DocBot/commit/53ede555e293d21f9fae37602f9f316f238634aa)
