### ISSUE TITLE
Verbose -v -V concern

### ISSUE THREAD

**Issue by cduarte3** [Add00/DocBot#7]
Verbose logging currently uses -V, whereas version uses -version and -v. This may be confusing for users trying to access version output, as they may try an uppercase V and unintentionally end up using verbose logging.

**Comment by Add00** [comment]
This is a good point the alias for verbose has been swapped to `l` for loud in [Bug fixes](https://github.com/Add00/DocBot/commit/53ede555e293d21f9fae37602f9f316f238634aa)
