### ISSUE TITLE
Token flag | --token-usage or --t

### ISSUE THREAD

**Issue by cduarte3** [Add00/DocBot#8]
## To do:
- I would like to add a flag for --token-usage or -t. This will allow for for outputting to the terminal through use of stderr. It will display extra information pertaining to the number of tokens that were sent in the prompt and returned in the completion from DocBot in the interaction between the user and the AI model.

<br>

## Information:
- I would like to work on this issue and implement it into the project.
- I will be trying my best to follow the style of code you have written thus far.
- This is useful as we can get a better understanding of the interaction with the AI model, how much is being sent, received, etc.
- I will be researching into the token usage information for the Ollama service and the Gemma2 / Gemma2:2b model.

**Comment by Add00** [comment]
Sounds good, go head

**Comment by Add00** [comment]
Feature merged
